{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-eicu.demo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/eth-mds/eicu-demo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f38d2bb1276602a54712ab711f07b477031dc018c23605daa8caa062d412d51c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rlang
  run:
    - r-base
    - r-rlang

test:
  commands:
    - $R -e "library('eicu.demo')"           # [not win]
    - "\"%R%\" -e \"library('eicu.demo')\""  # [win]

about:
  home: https://physionet.org/content/eicu-crd-demo/2.0/
  dev_url: https://github.com/eth-mds/eicu-demo
  license: ODbL-1.0
  license_file: LICENSE.md
  summary: |
    The eICU Collaborative Research Database is a multi-center
    database comprised of deidentified health data for over 200,000 admissions
    to ICUs across the United States between 2014-2015. The database includes
    vital sign measurements, care plan documentation, severity of illness
    measures, diagnosis information, and treatment information. An open-access
    subset of eICU, comprising 2,500 unit stays selected from 20 of the larger
    hospitals in the eICU Collaborative Research Database is distributed under
    the Open Database License (ODbL) v1.0 and is provided as R package for
    convenience.
extra:
  recipe-maintainers:
    - mlondschien
    - conda-forge/r
